---
# note: In theory this Compose file could be made to work in production & development.
version: "3.9"

services:
  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    ports:
      - published: ${POSTGRES_PORT:-5432}
        target: 5432

  redis-db:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: redis-data
        target: /data
    ports:
      - published: ${REDIS_PORT:-6379}
        target: 6379

volumes:
  postgres-data:
  redis-data:
