---
# note: In theory this Compose file could be made to work in production & development.
version: "3.9"
name: fullstack-demo
include:
  - path: compose.common.yaml

# hint: If there are environment variables that *must* be set the below will make it so.
# x-required:
#   - "${REPO_DIR:?Path to repository root in the container}"

x-dev-volumes: &__dev_volumes
  - type: bind
    source: ..
    target: ${REPO_DIR:-/code}
  - type: volume
    source: vscode-home-dir
    target: /home/${UNAME:-app}/.vscode-server
  - type: volume
    source: vscode-root-dir
    target: /vscode

x-django: &__django_service
  build:
    context: ..
    dockerfile: .devcontainer/backend/Dockerfile
    target: dev
  env_file:
    - ../.env
    # - ../backend/.env
  volumes: *__dev_volumes
  depends_on:
    - postgres-db
    - redis-db
  entrypoint:
    - ${VENV_DIR:-/venv}/bin/python
    - -m
    - djproj
  command:
    - --help

x-celery: &__celery_service
  <<: *__django_service
  volumes_from:
    - django-dev
  entrypoint:
    - ${VENV_DIR:-/venv}/bin/python
    - -m
    - celery
    - --app=${CELERY_APP:-djproj.celery:app}

x-next: &__next_service
  build:
    context: ..
    dockerfile: .devcontainer/frontend/Dockerfile
    target: dev
  env_file:
    - ../.env
    # - ../frontend/.env
  volumes: *__dev_volumes
  depends_on:
    - django-dev
  entrypoint:
    - npm
  command:
    - --help

services:
  django-dev:
    <<: *__django_service
    command:
      - runserver
      - "${DJANGO_HOST:-0.0.0.0}:${DJANGO_PORT:-8000}"
    ports:
      - published: ${DJANGO_PORT:-8000}
        target: 8000

  celery-worker:
    <<: *__celery_service
    command:
      - worker
      - --events
      - --concurrency=${CELERY_WORKER_CONCURRENCY:-1}
      - --queues=${CELERY_WORKER_QUEUES:-general,schedule}

  celery-beat:
    <<: *__celery_service
    command:
      - beat
      # - --scheduler=django_celery_beat.schedulers:DatabaseScheduler

  celery-flower:
    <<: *__celery_service
    command:
      - flower
      - --address=${FLOWER_HOST:-0.0.0.0}
      - --port=${FLOWER_PORT:-5555}
    ports:
      - published: ${FLOWER_PORT:-5555}
        target: 5555

  next-dev:
    <<: *__next_service
    command:
      - run
      - dev
      - -H ${NEXT_HOST:-0.0.0.0}
      - -p ${NEXT_PORT:-3000}
    ports:
      - published: ${NEXT_PORT:-3000}
        target: 3000

  storybook-dev:
    <<: *__next_service
    command:
      - run
      - dev:sb
      - -h ${STORYBOOK_HOST:-0.0.0.0}
      - -p ${STORYBOOK_PORT:-6006}
    volumes_from:
      - next-dev
    ports:
      - published: ${STORYBOOK_PORT:-6006}
        target: 6006

volumes:
  vscode-home-dir:
  vscode-root-dir:
