---
version: "3.9"
name: fullstack-demo

# x-required:
#   - "${REPO_DIR:?Path to repository root in the container}"

x-code-mount:
  &__code_mount
  type: bind
  source: ..
  target: ${REPO_DIR:-/code}

x-django:
  &__django_service
  build:
    context: ..
    dockerfile: .devcontainer/backend/Dockerfile
    target: dev
  env_file:
    - ../.env
    # - ../backend/.env
  volumes:
    - *__code_mount
    - type: volume
      source: vscode-home-dir
      target: /home/app/.vscode-server
    - type: volume
      source: vscode-root-dir
      target: /vscode
    - type: volume
      source: venv-dir
      target: ${VENV_DIR:-/venv}
  depends_on:
    - postgres-db
    - redis-db
  entrypoint:
    - ${VENV_DIR:-/venv}/bin/python
    - -m
    - djproj
  command:
    - --help

x-celery:
  &__celery_service
  <<: *__django_service
  volumes_from:
    - django-server
  entrypoint:
    - ${VENV_DIR:-/venv}/bin/python
    - -m
    - celery
    - --app=${CELERY_APP:-djproj.celery:app}

x-next:
  &__next_service
  build:
    context: ..
    dockerfile: .devcontainer/frontend/Dockerfile
    target: dev
  env_file:
    - ../.env
    # - ../frontend/.env
  volumes:
    - *__code_mount
    - type: volume
      source: node-modules
      target: ${REPO_DIR:-/code}/frontend/node_modules
  depends_on:
    - django-server
  entrypoint:
    - npm
  command:
    - --help

services:
  django-server:
    <<: *__django_service
    command:
      - runserver
      - "${DJANGO_HOST:-0.0.0.0}:${DJANGO_PORT:-8000}"

    # # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:postgres-db

    # Add "forwardPorts": ["8000"] to **devcontainer.json** to forward Django locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${DJANGO_PORT:-8000}
        target: 8000

  celery-worker:
    <<: *__celery_service
    command:
      - worker
      - --events
      - --concurrency=${CELERY_WORKER_CONCURRENCY:-1}
      - --queues=${CELERY_WORKER_QUEUES:-general,schedule}

  celery-beat:
    <<: *__celery_service
    command:
      - beat
      # - --scheduler=django_celery_beat.schedulers:DatabaseScheduler

  celery-flower:
    <<: *__celery_service
    command:
      - flower
      - --address=${FLOWER_HOST:-0.0.0.0}
      - --port=${FLOWER_PORT:-5555}

    # Add "forwardPorts": ["5555"] to **devcontainer.json** to forward Flower locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${FLOWER_PORT:-5555}
        target: 5555

  next-server:
    <<: *__next_service
    command:
      - run
      - dev
      - -H ${NEXT_HOST:-0.0.0.0}
      - -p ${NEXT_PORT:-3000}

    # Add "forwardPorts": ["3000"] to **devcontainer.json** to forward next.js locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${NEXT_PORT:-3000}
        target: 3000

  storybook-server:
    <<: *__next_service
    command:
      - run
      - storybook
      - -h ${STORYBOOK_HOST:-0.0.0.0}
      - -p ${STORYBOOK_PORT:-6006}
    volumes_from:
      - next-server

    # Add "forwardPorts": ["6006"] to **devcontainer.json** to forward next.js locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${STORYBOOK_PORT:-6006}
        target: 6006

  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${POSTGRES_PORT:-5432}
        target: 5432

  redis-db:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: redis-data
        target: /data

    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward Redis locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${REDIS_PORT:-6379}
        target: 6379

volumes:
  node-modules:
  postgres-data:
  redis-data:
  venv-dir:
  vscode-home-dir:
  vscode-root-dir:
