---
version: "3.9"
name: fullstack-demo
include:
  - path: compose.common.yaml

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
    - type: bind
      source: ..
      target: ${REPO_DIR:-/code}
    depends_on:
      - postgres-db
      - redis-db
    command:
      - sleep
      - infinity

    ports:
      # Add "forwardPorts": ["8000"] to **devcontainer.json** to forward Django locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${DJANGO_PORT:-8000}
        target: 8000
      # Add "forwardPorts": ["5555"] to **devcontainer.json** to forward Flower locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${FLOWER_PORT:-5555}
        target: 5555
      # Add "forwardPorts": ["3000"] to **devcontainer.json** to forward next.js locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${NEXT_PORT:-3000}
        target: 3000
      # Add "forwardPorts": ["6006"] to **devcontainer.json** to forward storybook locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${STORYBOOK_PORT:-6006}
        target: 6006
