---
version: "3.9"
name: fullstack-demo

# x-required:
#   - "${REPO_DIR:?Path to repository root in the container}"

x-code-mount:
  &__code_mount
  type: bind
  source: ..
  target: ${REPO_DIR:-/code}

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/backend/Dockerfile
      target: dev
    env_file:
      - ../.env
      # - ../backend/.env
    volumes:
      - *__code_mount
      - type: volume
        source: vscode-home-dir
        target: /home/app/.vscode-server
      - type: volume
        source: vscode-root-dir
        target: /vscode
    depends_on:
      - postgres-db
      - redis-db
    command:
      - honcho
      - -f
      - ${REPO_DIR:-/code}/.devcontainer/backend/Procfile
      - start
      - django-server
      - celery-worker
      - celery-beat
      - celery-flower
    ports:
      # Add "forwardPorts": ["8000"] to **devcontainer.json** to forward Django locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${DJANGO_PORT:-8000}
        target: 8000
      # Add "forwardPorts": ["5555"] to **devcontainer.json** to forward Flower locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${FLOWER_PORT:-5555}
        target: 5555

  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/frontend/Dockerfile
      target: dev
    env_file:
      - ../.env
      # - ../frontend/.env
    volumes:
      - *__code_mount
      - type: volume
        source: vscode-home-dir
        target: /home/app/.vscode-server
      - type: volume
        source: vscode-root-dir
        target: /vscode
    depends_on:
      - backend
    command:
      - honcho
      - -f
      - ${REPO_DIR:-/code}/.devcontainer/frontend/Procfile
      - start
      - next-server
      - storybook-server
    ports:
      # Add "forwardPorts": ["3000"] to **devcontainer.json** to forward next.js locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${NEXT_PORT:-3000}
        target: 3000
      # Add "forwardPorts": ["6006"] to **devcontainer.json** to forward storybook locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      - published: ${STORYBOOK_PORT:-6006}
        target: 6006

  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${POSTGRES_PORT:-5432}
        target: 5432

  redis-db:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: redis-data
        target: /data

    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward Redis locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${REDIS_PORT:-6379}
        target: 6379

volumes:
  postgres-data:
  redis-data:
  vscode-home-dir:
  vscode-root-dir:
