---
version: "3.9"

services:
  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${POSTGRES_PORT:-5432}
        target: 5432

  redis-db:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: redis-data
        target: /data

    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward Redis locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - published: ${REDIS_PORT:-6379}
        target: 6379

volumes:
  postgres-data:
  redis-data:
