---
# note: This Compose file is only meant for local development.
version: "3.9"
name: fullstack-demo
include:
  - path: compose.common.yaml

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    env_file:
      - ../.env

    volumes:
      - type: bind
        source: ..
        target: ${REPO_DIR:-/code}

      # This will make subsequent `npm install` runs faster.
      - type: volume
        source: npm-cache
        target: /home/${UNAME:-app}/.npm

      # note: This is an anonymous volume. We want to mount a volume here to keep
      # host and container `node_modules` separate, but Compose does not delete
      # named volumes when stopping services. (And we want it deleted so changes
      # don't hang around and rebuilds give us what we expect.)
      - type: volume
        target: ${REPO_DIR:-/code}/frontend/node_modules

    depends_on:
      - postgres-db
      - redis-db

    command:
      - sleep
      - infinity

    ports:
      - published: ${NEXT_PORT:-3000}
        target: 3000
      - published: ${FLOWER_PORT:-5555}
        target: 5555
      - published: ${STORYBOOK_PORT:-6006}
        target: 6006
      - published: ${DJANGO_PORT:-8000}
        target: 8000

volumes:
  npm-cache:
