be: djproj runserver "${DJANGO_HOST}:${DJANGO_PORT}"

cw: celery -A djproj.celery:app worker --events --concurrency="${CELERY_WORKER_CONCURRENCY:-1}" --queues="${CELERY_WORKER_QUEUES:-general,schedule}"

cb: celery -A djproj.celery:app beat

cf: celery -A djproj.celery:app flower --address="${FLOWER_HOST:-0.0.0.0}" --port="${FLOWER_PORT:-5555}"

fe: npm run dev

sb: npm run dev:sb
